apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: node-kube-app
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: node-kube-app
    spec:
      containers:
        - name: node-kube-app
          image: prateepgedupudi/node-kube-app
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: node-kube-app-service
  labels:
    name: node-kube-app-service
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: node-kube-app
  type: LoadBalancer